include:
  remote: 'https://raw.githubusercontent.com/ebi-ait/gitlab-ci-templates/master/build-release-deploy.yml'

Unit Test:
  image: quay.io/ebi-ait/ingest-base-images:openjdk_11
  script:
    - ./gradlew test
  artifacts:
    reports:
      junit:
        - build/test-results/**/TEST-*.xml