apiVersion: v1
kind: Service
metadata:
  labels:
    role: ingestion
  name: ingest-state-tracking-service
  namespace: {{ .Values.environment }}-environment
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8999
  selector:
    app: ingest-state-tracking
  sessionAffinity: None
  type: ClusterIP
